Repository GEOFARL/online-dictionary, pull requests merged in 2024-03, with the labels that each got.

#43 feat: add automated release system to workflow od-41
  .github/workflows/ci.yml
Labels: enhancement, configuration

#44 fix: Set up automated release system od-41
  .github/workflows/release.yml
Labels: bug, configuration

#45 fix: Set up automated release system od-41
  .github/workflows/release.yml
Labels: bug

#47 chore: correct styles in workflow od-41
  .github/workflows/cd.yml
  .github/workflows/release.yml
  appspec.yml
  package.json
Labels: bug

#48 fix: Remove condition that blocking automatic release od-41
  .github/workflows/release.yml
Labels: bug

#50 feat: Set up password hashing od-27
  .github/workflows/release.yml
  package-lock.json
  package.json
  src/libs/modules/encrypt/base-encrypt.module.ts
  src/libs/modules/encrypt/encrypt.ts
  src/libs/modules/encrypt/libs/constants/constants.ts
  src/libs/modules/encrypt/libs/constants/salt-rounds.constant.ts
  src/libs/modules/encrypt/libs/types/encrypt.type.ts
  src/libs/modules/encrypt/libs/types/types.ts
  src/modules/auth/auth.service.ts
Labels: enhancement, backend

#53 feat: Change release system to 'google please' od-52
  .github/workflows/cd.yml
  .github/workflows/release.yml
  package.json
Labels: enhancement, configuration

#54 chore(main): release 1.0.0
  CHANGELOG.md
Labels: autorelease: pending

#59 fix: Add a build step when deploying to AWS od-58
  scripts/after_install.sh
Labels: bug, configuration

#62 feat: create footer component od-61
  src/client/public/css/base.css
  src/client/public/css/includes/footer.css
  src/client/public/css/pages/home.css
  src/views/includes/footer.ejs
  src/views/pages/index.ejs
Labels: frontend

#63 chore(main): release 1.2.0
  CHANGELOG.md
Labels: autorelease: pending

#65 feat: add cta and dictionary page od-64
  src/app.ts
  src/client/public/css/base.css
  src/client/public/css/components/button.css
  src/client/public/css/pages/dictionary.css
  src/client/public/css/pages/home.css
  src/libs/enums/page-title.enum.ts
  src/libs/enums/pages-path.enum.ts
  src/modules/dictionary/dictionary.controller.ts
  src/modules/dictionary/dictionary.ts
  src/modules/home/home.controller.ts
  src/views/components/button.ejs
  src/views/pages/dictionary.ejs
  src/views/pages/index.ejs
Labels: backend, frontend

#66 chore(main): release 1.3.0
  CHANGELOG.md
Labels: autorelease: pending

#69 chore(main): release 1.4.0
  CHANGELOG.md
Labels: autorelease: pending

#42 feat: style for home page od-34
  src/client/public/css/base.css
  src/client/public/css/pages/home.css
  src/views/pages/index.ejs
Labels: frontend

#72 chore(main): release 1.5.0
  CHANGELOG.md
Labels: autorelease: pending

#55 feat: sign in page markup od-25
  src/client/public/css/base.css
  src/client/public/css/components/button.css
  src/client/public/css/components/input.css
  src/client/public/css/components/link.css
  src/client/public/css/components/separator.css
  src/client/public/css/pages/sign-in.css
  src/client/public/icons/eye-closed.svg
  src/client/public/icons/eye-visible.svg
  src/client/src/pages/sign-in/sign-in.ts
  src/client/src/shared/index.ts
  src/client/src/shared/libs/helpers/helpers.ts
  src/client/src/shared/libs/helpers/init-password-toggle.ts
  src/client/src/shared/libs/modules/dom/base-dom.module.ts
  src/client/src/shared/libs/modules/dom/libs/types/dom.type.ts
  src/views/components/link.ejs
  src/views/components/separator.ejs
  src/views/pages/sign-in.ejs
Labels: frontend

#73 chore(main): release 1.6.0
  CHANGELOG.md
Labels: autorelease: pending

#76 feat: Render word result search od-71
  src/client/public/assets/icons/audio.svg
  src/client/public/css/base.css
  src/client/public/css/pages/dictionary.css
  src/client/src/pages/dictionary/dictionary.ts
  src/client/src/shared/index.ts
  src/client/src/shared/libs/constants/constants.ts
  src/client/src/shared/libs/constants/hidden-class.constant.ts
  src/client/src/shared/libs/helpers/helpers.ts
  src/client/src/shared/libs/helpers/hide-element.helper.ts
  src/client/src/shared/libs/helpers/show-element.helper.ts
  src/client/src/shared/libs/maps/maps.ts
  src/client/src/shared/libs/maps/part-of-speech-to-class-name.map.ts
  src/client/src/shared/libs/modules/dom/base-dom.module.ts
  src/client/src/shared/libs/modules/dom/libs/types/dom.type.ts
  src/client/src/shared/libs/types/part-of-speech.type.ts
  src/client/src/shared/libs/types/types.ts
  src/modules/dictionary/libs/helpers/map-dictionary-response-to-word.helper.ts
  src/views/pages/dictionary.ejs
Labels: enhancement, frontend

#78 feat: prevent registration of users with the same email od-29
  src/libs/exceptions/libs/enums/exception-message.enum.ts
  src/modules/auth/auth.service.ts
Labels: enhancement, backend

#80 chore(main): release 1.8.0
  CHANGELOG.md
Labels: autorelease: pending

#70 feat: add sign up page styles and markup od-26
  src/client/public/css/pages/sign-up.css
  src/client/src/pages/sign-up/sign-up.ts
  src/views/components/input.ejs
  src/views/pages/sign-up.ejs
Labels: frontend

#87 chore(main): release 1.9.0
  CHANGELOG.md
Labels: autorelease: pending

#91 feat: Add word definitions od-79
  src/client/public/css/base.css
  src/client/public/css/pages/dictionary.css
  src/client/public/css/pages/home.css
  src/client/src/pages/dictionary/dictionary.ts
  src/views/pages/dictionary.ejs
Labels: enhancement, frontend

#92 chore(main): release 1.10.0
  CHANGELOG.md
Labels: autorelease: pending

#95 fix: add link underline on hover od-90
  src/client/public/css/components/link.css
Labels: bug

#97 chore(main): release 1.10.1
  CHANGELOG.md
Labels: autorelease: pending

#99 feat: Add Request logging to the server od-75
  src/app.ts
  src/middlewares/error-handler/error-handler.middleware.ts
  src/middlewares/http-logger/http-logger.middleware.ts
  src/middlewares/http-logger/http-logger.ts
  src/middlewares/middlewares.ts
Labels: backend, configuration

#100 chore(main): release 1.11.0
  CHANGELOG.md
Labels: autorelease: pending

#104 feat: Make sign in and sign up pages inaccessible if the user is logged in od-74
  src/app.ts
  src/client/src/pages/home/home.ts
  src/client/src/shared/libs/enums/enums.ts
  src/libs/enums/api-path.enum.ts
  src/libs/enums/cookie.enum.ts
  src/libs/enums/enums.ts
  src/libs/modules/server-application/base-server-application.module.ts
  src/middlewares/inject-data/inject-data.middleware.ts
  src/middlewares/inject-data/inject-data.ts
  src/middlewares/middlewares.ts
  src/modules/auth/auth.controller.ts
  src/modules/dictionary/dictionary.controller.ts
  src/modules/home/home.controller.ts
  src/views/pages/index.ejs
Labels: enhancement, backend, frontend

#105 chore(main): release 1.12.0
  CHANGELOG.md
Labels: autorelease: pending

#96 feat: add mobile responsiveness for sign up page od-86
  src/client/public/css/components/button.css
  src/client/public/css/components/input.css
  src/client/public/css/pages/sign-up.css
  src/views/components/separator.ejs
  src/views/pages/sign-up.ejs
Labels: enhancement, frontend

#106 chore(main): release 1.13.0
  CHANGELOG.md
Labels: autorelease: pending

#101 feat: create a hero section of the page od-82
  src/client/public/assets/icons/bullet-list.svg
  src/client/public/assets/images/hero-image.png
  src/client/public/css/pages/home.css
  src/views/pages/index.ejs
Labels: enhancement, frontend

#107 chore(main): release 1.14.0
  CHANGELOG.md
Labels: autorelease: pending

#110 fix: Make auth possible only with valid password od-103
  src/libs/modules/encrypt/base-encrypt.module.ts
  src/modules/auth/auth.service.ts
Labels: bug, backend

#111 chore(main): release 1.14.1
  CHANGELOG.md
Labels: autorelease: pending

#112 feat: Add a loader component od-83
  src/client/public/css/base.css
  src/client/public/css/components/loader.css
  src/client/public/css/pages/dictionary.css
  src/client/src/pages/dictionary/dictionary.ts
  src/views/components/loader.ejs
  src/views/pages/dictionary.ejs
Labels: enhancement, frontend

#113 chore(main): release 1.15.0
  CHANGELOG.md
Labels: autorelease: pending

#115 feat: Handle the case when the word does not exist or not found od-84
  src/client/public/assets/icons/eye-closed.svg
  src/client/public/assets/icons/eye-visible.svg
  src/client/public/assets/images/shocked-black-guy.png
  src/client/public/css/base.css
  src/client/public/css/pages/dictionary.css
  src/client/public/css/pages/sign-in.css
  src/client/public/css/pages/sign-up.css
  src/client/src/pages/dictionary/dictionary.ts
  src/middlewares/middlewares.ts
  src/middlewares/validate/validate.middleware.ts
  src/modules/dictionary/dictionary.controller.ts
  src/modules/dictionary/dictionary.service.ts
  src/modules/dictionary/libs/enums/dictionary-api-error-title.enum.ts
  src/modules/dictionary/libs/enums/dictionary-validation-message.enum.ts
  src/modules/dictionary/libs/enums/dictionary-validation-rule.enum.ts
  src/modules/dictionary/libs/enums/enums.ts
  src/modules/dictionary/libs/enums/exception-message.enum.ts
  src/modules/dictionary/libs/validation-schemas/validation-schemas.ts
  src/modules/dictionary/libs/validation-schemas/word-search.validation-schema.ts
  src/views/pages/dictionary.ejs
  src/views/pages/sign-in.ejs
  src/views/pages/sign-up.ejs
Labels: enhancement, backend, frontend

#116 chore(main): release 1.16.0
  CHANGELOG.md
Labels: autorelease: pending

#118 feat: Create Not Found page and return it if the user enters invalid URL od-102
  src/app.ts
  src/client/public/css/pages/not-found.css
  src/libs/enums/page-title.enum.ts
  src/libs/enums/pages-path.enum.ts
  src/libs/modules/server-application/base-server-application.module.ts
  src/views/pages/not-found.ejs
Labels: enhancement, backend, frontend

#120 chore(main): release 1.17.0
  CHANGELOG.md
Labels: autorelease: pending

#98 feat: sign in page responsiveness od-85
  src/client/public/css/pages/sign-in.css
  src/views/pages/sign-in.ejs
Labels: enhancement, frontend

#121 chore(main): release 1.18.0
  CHANGELOG.md
Labels: autorelease: pending

#125 feat: Add a block with synonyms od-94
  src/client/public/css/base.css
  src/client/public/css/pages/dictionary.css
  src/client/src/pages/dictionary/dictionary.ts
  src/client/src/pages/dictionary/libs/helpers/helpers.ts
  src/client/src/pages/dictionary/libs/helpers/render-synonyms.helper.ts
  src/client/src/pages/dictionary/libs/helpers/render-word-definition.helper.ts
  src/client/src/pages/dictionary/libs/helpers/reset-search-input.helper.ts
  src/client/src/pages/dictionary/libs/helpers/show-loading-state.helper.ts
  src/client/src/pages/dictionary/libs/helpers/show-not-found.helper.ts
  src/client/src/pages/dictionary/libs/helpers/show-search-results.helper.ts
  src/client/src/pages/dictionary/libs/modules/audio/audio.ts
  src/client/src/pages/dictionary/libs/modules/audio/base-audio.module.ts
  src/client/src/pages/dictionary/libs/modules/modules.ts
  src/client/src/shared/index.ts
  src/client/src/shared/libs/constants/constants.ts
  src/client/src/shared/libs/constants/divisor-for-parity.constant.ts
  src/client/src/shared/libs/modules/dom/base-dom.module.ts
  src/client/src/shared/libs/modules/dom/libs/types/create-element-options.type.ts
  src/client/src/shared/libs/modules/dom/libs/types/dom.type.ts
  src/client/src/shared/libs/modules/dom/libs/types/types.ts
  src/views/pages/dictionary.ejs
Labels: frontend, feature

#126 chore(main): release 1.19.0
  CHANGELOG.md
Labels: autorelease: pending

#119 feat: add return back to home page links od-109
  src/client/public/css/pages/sign-in.css
  src/client/public/css/pages/sign-up.css
  src/modules/auth/auth.controller.ts
  src/views/pages/sign-in.ejs
  src/views/pages/sign-up.ejs
Labels: enhancement, frontend

#127 chore(main): release 1.20.0
  CHANGELOG.md
Labels: autorelease: pending

#133 feat: Enable word search by using a query in the URL od-132
  src/client/src/pages/dictionary/dictionary.ts
  src/client/src/pages/dictionary/libs/helpers/render-word-definition.helper.ts
Labels: enhancement, frontend

#134 chore(main): release 1.21.0
  CHANGELOG.md
Labels: autorelease: pending

#135 feat: Add associated image to the search result od-114
  .env.example
  knip.json
  package-lock.json
  package.json
  src/client/public/css/components/swiper.css
  src/client/public/css/pages/dictionary.css
  src/client/src/pages/dictionary/dictionary.ts
  src/client/src/pages/dictionary/libs/helpers/render-word-definition.helper.ts
  src/client/src/pages/dictionary/libs/helpers/show-loading-state.helper.ts
  src/client/src/pages/dictionary/libs/helpers/show-search-results.helper.ts
  src/client/src/pages/dictionary/libs/modules/modules.ts
  src/client/src/pages/dictionary/libs/modules/swiper/swiper.ts
  src/client/src/shared/libs/modules/navigation/base-navigation.module.ts
  src/libs/modules/config/base-config.module.ts
  src/libs/modules/config/libs/types/environment-schema.type.ts
  src/libs/modules/pexels/base-pexels.module.ts
  src/libs/modules/pexels/libs/constants/constants.ts
  src/libs/modules/pexels/libs/constants/default-number-of-images.constant.ts
  src/libs/modules/pexels/libs/helpers/check-if-is-photos.helper.ts
  src/libs/modules/pexels/libs/helpers/helpers.ts
  src/libs/modules/pexels/libs/types/image-dto.type.ts
  src/libs/modules/pexels/libs/types/pexels.type.ts
  src/libs/modules/pexels/libs/types/types.ts
  src/libs/modules/pexels/pexels.ts
  src/modules/dictionary/dictionary.service.ts
  src/modules/dictionary/libs/helpers/map-dictionary-response-to-word.helper.ts
  src/modules/dictionary/libs/types/word-dto.type.ts
  src/views/components/swiper.ejs
  src/views/pages/dictionary.ejs
Labels: backend, frontend, feature

#136 chore(main): release 1.22.0
  CHANGELOG.md
Labels: autorelease: pending

#137 chore: Add associated image to the search result od-114
  src/client/src/pages/dictionary/libs/modules/swiper/swiper.ts
  src/client/src/shared/libs/modules/navigation/base-navigation.module.ts
Labels: enhancement

#122 feat: create a review component od-81
  src/client/public/assets/images/default-review-profile-picture.png
  src/client/public/css/components/review.css
  src/views/components/review.ejs
  src/views/includes/head.ejs
  src/views/pages/index.ejs
Labels: enhancement, frontend

#139 chore(main): release 1.23.0
  CHANGELOG.md
Labels: autorelease: pending
