Repository GEOFARL/online-dictionary, pull requests merged in 2024-05, with the labels that each got.

#226 feat: Add the ability to save and delete words as your favourites od-216
  README.md
  src/client/src/pages/explore/explore.ts
  src/client/src/shared/libs/enums/notification-message.enum.ts
  src/client/src/shared/libs/helpers/configure-user-menu.ts
  src/libs/enums/api-path.enum.ts
  src/libs/modules/api/base-api.ts
  src/libs/modules/api/libs/types/api.type.ts
  src/libs/modules/db/migrations/20240501035702-favorite-words.cjs
  src/libs/modules/db/models/associations.ts
  src/libs/modules/db/models/user.model.ts
  src/libs/modules/server-application/base-server-application.module.ts
  src/modules/dictionary/dictionary.controller.ts
  src/modules/dictionary/dictionary.repository.ts
  src/modules/dictionary/dictionary.service.ts
  src/modules/dictionary/dictionary.ts
  src/modules/explore/explore.controller.ts
  src/modules/explore/explore.service.ts
  src/modules/user/user.repository.ts
  src/modules/user/user.service.ts
  src/views/pages/explore.ejs
Labels: backend, frontend, feature

#227 chore(main): release 1.48.0
  CHANGELOG.md
Labels: autorelease: pending

#228 feat: make settings page responsive od-215
  src/client/public/css/pages/settings.css
Labels: enhancement, frontend

#230 chore(main): release 1.49.0
  CHANGELOG.md
Labels: autorelease: pending

#229 feat: add default image placeholder od-224
  src/client/public/assets/icons/image-not-found.svg
  src/client/public/css/components/swiper.css
  src/client/src/pages/dictionary/libs/constants/constants.ts
  src/client/src/pages/dictionary/libs/constants/min-array-length.constant.ts
  src/client/src/pages/dictionary/libs/helpers/render-word-definition.helper.ts
Labels: enhancement, frontend

#231 chore(main): release 1.50.0
  CHANGELOG.md
Labels: autorelease: pending

#233 chore(main): release 1.51.0
  CHANGELOG.md
Labels: autorelease: pending

#234 feat: Add the possibility to filter the words by their part of the language od-218
  src/client/public/css/base.css
  src/client/public/css/pages/favorites.css
  src/client/src/pages/favorites/favorites.ts
  src/client/src/shared/index.ts
  src/libs/enums/api-path.enum.ts
  src/modules/dictionary/dictionary.controller.ts
  src/modules/dictionary/dictionary.service.ts
  src/modules/user/user.repository.ts
  src/modules/user/user.service.ts
  src/views/pages/favorites.ejs
Labels: backend, frontend, feature

#235 chore(main): release 1.52.0
  CHANGELOG.md
Labels: autorelease: pending

#236 feat: Add an infinite scroll pagination od-219
  src/client/src/pages/favorites/favorites.ts
  src/client/src/pages/favorites/libs/helpers/helpers.ts
  src/client/src/pages/favorites/libs/helpers/render-word.helper.ts
  src/libs/constants/constants.ts
  src/libs/constants/default-page-size.constant.ts
  src/modules/dictionary/dictionary.controller.ts
  src/modules/dictionary/dictionary.service.ts
  src/modules/user/user.repository.ts
  src/modules/user/user.service.ts
Labels: backend, frontend, feature

#237 chore(main): release 1.53.0
  CHANGELOG.md
Labels: autorelease: pending
