Repository GEOFARL/online-dictionary, pull requests merged in 2024-04, with the labels that each got.

#124 feat: navigation component od-28
  src/client/public/assets/images/website-logo.svg
  src/client/public/css/includes/navigation.css
  src/client/public/css/pages/dictionary.css
  src/modules/dictionary/dictionary.controller.ts
  src/modules/home/home.controller.ts
  src/views/components/link.ejs
  src/views/includes/navigation.ejs
  src/views/pages/dictionary.ejs
  src/views/pages/index.ejs
Labels: backend, frontend, feature

#141 chore(main): release 1.24.0
  CHANGELOG.md
Labels: autorelease: pending

#138 feat: add brurred background on main and dictionary pages od-108
  src/client/public/assets/images/hero-image.png
  src/client/public/css/includes/overlay.css
  src/client/public/css/pages/home.css
  src/views/includes/overlay.ejs
  src/views/pages/dictionary.ejs
  src/views/pages/index.ejs
Labels: frontend, feature

#142 chore(main): release 1.25.0
  CHANGELOG.md
Labels: autorelease: pending

#145 feat: Add word of the day section od-89
  .eslintrc.js
  package-lock.json
  package.json
  src/app.ts
  src/client/public/assets/images/placeholder-image.jpg
  src/client/public/css/base.css
  src/client/public/css/includes/badges.css
  src/client/public/css/pages/dictionary.css
  src/client/public/css/pages/explore.css
  src/client/src/pages/explore/explore.ts
  src/libs/constants/application-name.constant.ts
  src/libs/constants/constants.ts
  src/libs/constants/last-array-element.constant.ts
  src/libs/enums/page-title.enum.ts
  src/libs/enums/pages-path.enum.ts
  src/libs/helpers/capitalize.helper.ts
  src/libs/helpers/helpers.ts
  src/libs/modules/db/base-db.module.ts
  src/libs/modules/db/db.ts
  src/libs/modules/db/libs/enums/table-name.enum.ts
  src/libs/modules/random-words/base-random-words.module.ts
  src/libs/modules/random-words/libs/types/random-words.type.ts
  src/libs/modules/random-words/libs/types/types.ts
  src/libs/modules/random-words/random-words.ts
  src/libs/modules/server-application/base-server-application.module.ts
  src/libs/modules/task-scheduler/base-task-scheduler.module.ts
  src/libs/modules/task-scheduler/libs/enums/cron-expression.enum.ts
  src/libs/modules/task-scheduler/libs/enums/enums.ts
  src/libs/modules/task-scheduler/libs/types/task-scheduler.type.ts
  src/libs/modules/task-scheduler/libs/types/types.ts
  src/libs/modules/task-scheduler/task-scheduler.ts
  src/modules/dictionary/dictionary.controller.ts
  src/modules/dictionary/dictionary.ts
  src/modules/dictionary/libs/types/types.ts
  src/modules/dictionary/libs/types/word-of-the-day-dto.type.ts
  src/modules/explore/explore.controller.ts
  src/modules/explore/explore.repository.ts
  src/modules/explore/explore.service.ts
  src/modules/explore/explore.ts
  src/modules/home/home.controller.ts
  src/views/includes/navigation.ejs
  src/views/pages/dictionary.ejs
  src/views/pages/explore.ejs
Labels: backend, frontend, feature

#146 chore(main): release 1.26.0
  CHANGELOG.md
Labels: autorelease: pending

#148 fix: Production build fail due to ES modules od-147
  .eslintrc.cjs
  commitlint.config.cjs
  lint-staged.config.cjs
  package.json
  scripts/after_install.sh
  src/client/.eslintrc.cjs
  tsconfig.json
Labels: bug

#149 chore(main): release 1.26.1
  CHANGELOG.md
Labels: autorelease: pending

#150 fix: Production build fail due to ES modules od-147
  src/libs/modules/db/base-db.module.ts
  src/middlewares/inject-data/inject-data.middleware.ts
Labels: bug

#151 chore(main): release 1.26.2
  CHANGELOG.md
Labels: autorelease: pending

#155 chore(main): release 1.26.3
  CHANGELOG.md
Labels: autorelease: pending

#156 feat: Add a placeholder for a dictionary page od-152
  src/client/public/css/pages/dictionary.css
  src/client/src/pages/dictionary/libs/helpers/show-loading-state.helper.ts
  src/views/pages/dictionary.ejs
Labels: enhancement, frontend

#157 chore(main): release 1.27.0
  CHANGELOG.md
Labels: autorelease: pending

#158 feat: Add OG protocol to the website od-117
  src/client/public/assets/images/og-image.png
  src/views/includes/head.ejs
Labels: enhancement

#159 chore(main): release 1.28.0
  CHANGELOG.md
Labels: autorelease: pending

#161 feat: Add Fav Icon to the website od-160
  src/client/public/assets/images/website-logo.ico
  src/views/includes/head.ejs
Labels: enhancement, frontend

#162 chore(main): release 1.29.0
  CHANGELOG.md
Labels: autorelease: pending

#163 feat: Show recently viewed words od-88
  src/client/public/css/pages/explore.css
  src/modules/dictionary/dictionary.repository.ts
  src/modules/dictionary/dictionary.service.ts
  src/modules/dictionary/libs/constants/constants.ts
  src/modules/dictionary/libs/constants/maximum-number-of-latest-words.constant.ts
  src/modules/explore/explore.controller.ts
  src/modules/explore/explore.service.ts
  src/views/pages/explore.ejs
Labels: backend, frontend, feature

#164 chore(main): release 1.30.0
  CHANGELOG.md
Labels: autorelease: pending

#140 feat: add at least 4 default reviews od-128
  src/client/public/assets/images/default-review-profile-picture.png
  src/client/public/css/pages/home.css
  src/libs/exceptions/libs/enums/exception-message.enum.ts
  src/libs/helpers/helpers.ts
  src/libs/helpers/select-random-items.helper.ts
  src/modules/home/home.controller.ts
  src/modules/home/libs/constants/constants.ts
  src/modules/home/libs/constants/number-of-reviews-to-render.constant.ts
  src/modules/home/libs/constants/reviews.constant.ts
  src/modules/home/libs/types/review-dto.type.ts
  src/modules/home/libs/types/types.ts
  src/views/pages/index.ejs
Labels: backend, frontend, feature

#166 chore(main): release 1.31.0
  CHANGELOG.md
Labels: autorelease: pending

#154 feat: add fixed width to logo od-143
  src/client/public/css/components/navigation.css
Labels: bug

#167 chore(main): release 1.32.0
  CHANGELOG.md
Labels: autorelease: pending

#169 feat: Make word not found page mobile responsive od-168
  src/client/public/css/includes/overlay.css
  src/client/public/css/pages/dictionary.css
  src/views/pages/explore.ejs
Labels: enhancement, frontend

#170 chore(main): release 1.33.0
  CHANGELOG.md
Labels: autorelease: pending

#172 feat: Make footer mobile responsive od-171
  src/client/public/css/includes/footer.css
Labels: enhancement, frontend

#173 chore(main): release 1.34.0
  CHANGELOG.md
Labels: autorelease: pending

#176 feat: Make not found page mobile responsive od-174
  src/client/public/css/base.css
  src/client/public/css/pages/not-found.css
Labels: enhancement, frontend

#177 chore(main): release 1.35.0
  CHANGELOG.md
Labels: autorelease: pending

#165 feat: mobile sidebar od-131
  src/client/public/assets/icons/burger.svg
  src/client/public/assets/icons/close.svg
  src/client/public/assets/icons/dictionary.svg
  src/client/public/assets/icons/home.svg
  src/client/public/assets/icons/world.svg
  src/client/public/css/components/navigation.css
  src/client/public/css/components/sidebar.css
  src/client/src/pages/dictionary/dictionary.ts
  src/client/src/pages/explore/explore.ts
  src/client/src/pages/home/home.ts
  src/client/src/shared/index.ts
  src/client/src/shared/libs/helpers/configure-mobile-sidebar.ts
  src/client/src/shared/libs/helpers/helpers.ts
  src/views/components/button.ejs
  src/views/components/navigation.ejs
  src/views/components/sidebar.ejs
  src/views/pages/dictionary.ejs
  src/views/pages/explore.ejs
  src/views/pages/index.ejs
Labels: enhancement, frontend

#178 chore(main): release 1.36.0
  CHANGELOG.md
Labels: autorelease: pending

#179 feat: Make dictionary page mobile responsive od-175
  src/client/public/css/includes/badges.css
  src/client/public/css/pages/dictionary.css
  src/client/src/pages/dictionary/dictionary.ts
  src/client/src/pages/dictionary/libs/helpers/render-word-definition.helper.ts
  src/client/src/pages/dictionary/libs/modules/swiper/swiper.ts
  src/client/src/pages/explore/explore.ts
  src/client/src/pages/home/home.ts
  src/views/pages/dictionary.ejs
Labels: enhancement, frontend

#180 chore(main): release 1.37.0
  CHANGELOG.md
Labels: autorelease: pending

#182 fix: large world icon od-181
  src/client/public/css/components/sidebar.css
Labels: bug

#183 chore(main): release 1.37.1
  CHANGELOG.md
Labels: autorelease: pending

#185 feat: Set up layout for the main page od-129
  src/client/public/css/pages/home.css
  src/views/pages/index.ejs
Labels: frontend

#186 chore(main): release 1.38.0
  CHANGELOG.md
Labels: autorelease: pending

#187 feat: Make Explore page mobile responsive od-184
  src/client/public/css/pages/explore.css
Labels: enhancement, frontend

#188 chore(main): release 1.39.0
  CHANGELOG.md
Labels: autorelease: pending

#189 feat: Add mobile responsiveness for the home page od-130
  src/client/public/css/base.css
  src/client/public/css/pages/home.css
Labels: enhancement, frontend

#190 chore(main): release 1.40.0
  CHANGELOG.md
Labels: autorelease: pending

#194 feat: Replace working with data via files with DB without using ORM od-193
  .env.example
  README.md
  package-lock.json
  package.json
  scripts/init_db.sh
  src/libs/modules/config/base-config.module.ts
  src/libs/modules/config/libs/types/environment-schema.type.ts
  src/libs/modules/db/base-db.module.ts
  src/libs/modules/db/db.ts
  src/libs/modules/db/libs/constants/constants.ts
  src/libs/modules/db/libs/constants/id-byte-length.constant.ts
  src/libs/modules/db/libs/constants/storage-name.constant.ts
  src/libs/modules/db/libs/types/db-record.type.ts
  src/middlewares/error-handler/error-handler.middleware.ts
  src/modules/auth/auth.repository.ts
  src/modules/auth/auth.service.ts
  src/modules/dictionary/dictionary.repository.ts
  src/modules/dictionary/dictionary.service.ts
  src/modules/dictionary/libs/types/word-record-dto.type.ts
  src/modules/explore/explore.repository.ts
  src/modules/user/libs/types/user-auth-sign-up-request-dto.type.ts
  src/modules/user/libs/types/user-dto.type.ts
  src/views/pages/explore.ejs
Labels: backend, configuration, docs

#195 chore(main): release 1.41.0
  CHANGELOG.md
Labels: autorelease: pending

#196 fix: db connection od-193
  scripts/init_db.sh
  src/libs/modules/config/base-config.module.ts
  src/libs/modules/db/base-db.module.ts
Labels: bug, configuration

#199 fix: Replace working with data via files with DB without using ORM od-193
  src/libs/modules/db/base-db.module.ts
  src/libs/modules/db/db.ts
Labels: bug, backend, configuration

#200 chore(main): release 1.41.2
  CHANGELOG.md
Labels: autorelease: pending

#204 chore(main): release 1.42.0
  CHANGELOG.md
Labels: autorelease: pending

#206 chore(main): release 1.43.0
  CHANGELOG.md
Labels: autorelease: pending

#209 feat: Implement profile update route and logic od-207
  src/app.ts
  src/client/src/pages/settings/settings.ts
  src/client/src/pages/sign-in/sign-in.ts
  src/client/src/pages/sign-up/sign-up.ts
  src/client/src/shared/index.ts
  src/client/src/shared/libs/enums/enums.ts
  src/client/src/shared/libs/enums/notification-message.enum.ts
  src/libs/enums/api-path.enum.ts
  src/libs/modules/api/base-api.ts
  src/libs/modules/api/libs/types/api.type.ts
  src/libs/modules/db/base-db.module.ts
  src/libs/modules/db/libs/types/db.type.ts
  src/libs/modules/http/libs/types/http-method.type.ts
  src/middlewares/authenticate/authenticate.middleware.ts
  src/middlewares/authenticate/authenticate.ts
  src/modules/auth/auth.controller.ts
  src/modules/auth/auth.service.ts
  src/modules/auth/auth.ts
  src/modules/user/libs/enums/exception-message.enum.ts
  src/modules/user/libs/types/types.ts
  src/modules/user/libs/types/user-profile-update-request-dto.type.ts
  src/modules/user/libs/types/user-profile-update-response-dto.type.ts
  src/modules/user/libs/validation-schemas/user-profile-update.validation-schema.ts
  src/modules/user/user.controller.ts
  src/modules/user/user.repository.ts
  src/modules/user/user.service.ts
  src/modules/user/user.ts
  src/views/pages/settings.ejs
Labels: backend, feature

#210 chore(main): release 1.44.0
  CHANGELOG.md
Labels: autorelease: pending

#211 feat: Implement profile deletion functionality od-208
  src/client/public/css/pages/settings.css
  src/client/src/pages/settings/settings.ts
  src/client/src/shared/libs/enums/notification-message.enum.ts
  src/libs/modules/api/base-api.ts
  src/libs/modules/api/libs/types/api.type.ts
  src/libs/modules/db/base-db.module.ts
  src/libs/modules/db/libs/types/db.type.ts
  src/modules/user/user.controller.ts
  src/modules/user/user.repository.ts
  src/modules/user/user.service.ts
  src/views/pages/settings.ejs
Labels: backend, frontend, feature

#212 chore(main): release 1.45.0
  CHANGELOG.md
Labels: autorelease: pending

#220 feat: Add transactions to the creation, deletion and modification methods od-213
  src/libs/modules/db/base-db.module.ts
Labels: enhancement, backend

#221 chore(main): release 1.46.0
  CHANGELOG.md
Labels: autorelease: pending

#223 chore(main): release 1.47.0
  CHANGELOG.md
Labels: autorelease: pending
